<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Australia</name>
   <tag></tag>
   <elementGuidId>5700ec8d-97da-488b-961b-b9970f8a5ef3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.navFooterLine.navFooterLinkLine.navFooterPadItemLine > ul > li.nav_first > a.nav_a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navFooter']/div[4]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2e7ce545-741b-4124-86c2-52cbf4f7c9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.com.au/ref=footer_au</value>
      <webElementGuid>3cad7eee-7c9c-4a5b-8b72-242fde9cfd66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav_a</value>
      <webElementGuid>47cac8c2-e64c-418a-b3d0-3f6d4721a555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Australia</value>
      <webElementGuid>c8a94bad-944a-4bb1-a300-561bcf31d0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navFooter&quot;)/div[@class=&quot;navFooterLine navFooterLinkLine navFooterPadItemLine&quot;]/ul[1]/li[@class=&quot;nav_first&quot;]/a[@class=&quot;nav_a&quot;]</value>
      <webElementGuid>a12d7fd9-7469-4762-9706-ec1d7b232643</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navFooter']/div[4]/ul/li/a</value>
      <webElementGuid>0beadabb-1de3-4299-bcc4-e41a781f13bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Australia')]</value>
      <webElementGuid>555ff4d6-ea84-48fa-8918-09566e4a2bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.com.au/ref=footer_au')]</value>
      <webElementGuid>9cdb6a92-f2d4-4a12-b97d-91860e71a863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li/a</value>
      <webElementGuid>90726951-2a14-435b-8fd3-4958eb00235c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.amazon.com.au/ref=footer_au' and (text() = 'Australia' or . = 'Australia')]</value>
      <webElementGuid>fe291afb-cd88-4c90-af44-44b6fbb52889</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
