<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Japan</name>
   <tag></tag>
   <elementGuidId>1885ab25-c30e-4d3b-b3b5-3163e0e356d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.navFooterLine.navFooterLinkLine.navFooterPadItemLine > ul > li:nth-of-type(8) > a.nav_a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navFooter']/div[4]/ul/li[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6ed60ac6-122f-4371-86af-4578c8c9cc34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.co.jp/ref=footer_jp</value>
      <webElementGuid>bc298617-90df-4825-9e1f-042a85f9fc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav_a</value>
      <webElementGuid>e2a06bba-8e35-400b-a28a-97d7638f887b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Japan</value>
      <webElementGuid>76590cd7-bfae-43b4-ad7f-1742f060c352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navFooter&quot;)/div[@class=&quot;navFooterLine navFooterLinkLine navFooterPadItemLine&quot;]/ul[1]/li[8]/a[@class=&quot;nav_a&quot;]</value>
      <webElementGuid>c0f8654e-9031-4dd2-9570-8d7224d9167a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navFooter']/div[4]/ul/li[8]/a</value>
      <webElementGuid>6ae5e266-89a3-41c1-88f1-39204ee1517f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Japan')]</value>
      <webElementGuid>7cdb27b1-a394-4fcb-b43b-22729992db6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.co.jp/ref=footer_jp')]</value>
      <webElementGuid>e66f8ea2-4c06-4342-8874-87a465ef57b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[8]/a</value>
      <webElementGuid>29657a6b-5351-4b19-a60d-325f389f2c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.amazon.co.jp/ref=footer_jp' and (text() = 'Japan' or . = 'Japan')]</value>
      <webElementGuid>6f6d31f1-dbf4-4147-87e1-ddf5693d6fc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
