<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Prime</name>
   <tag></tag>
   <elementGuidId>8649e189-71b4-4cb5-b173-588a36ae2c07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-link-amazonprime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-link-amazonprime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5b25b0bd-2073-415f-bff8-f0e8a41bfe2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/prime?ref_=nav_cs_primelink_nonmember</value>
      <webElementGuid>cb28a8b1-ea8d-4dd8-9098-7cf8802c7840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a   nav-active</value>
      <webElementGuid>37f3c1ad-5356-4c45-92b7-254723816113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ux-jq-mouseenter</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0fc05a6d-5ab3-4894-b56d-d9c8a6379734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-link-amazonprime</value>
      <webElementGuid>9a3c0f67-7b7b-41f5-8178-efd212f7af38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b93c19f1-f1c8-4695-a6bf-62ab022f1562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>1864023e-f226-4e3e-a6ef-6941efee295b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>nav-link-amazonprime</value>
      <webElementGuid>d0eeeefc-b1e9-4ca1-8377-36c99d0ac17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>nav_cs_primelink_nonmember</value>
      <webElementGuid>4e03949d-cd25-47df-9eec-088b39b43541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>xt39vx-ljnhd9-4lmrhy-a2ftv6</value>
      <webElementGuid>b3b1b2d9-1e4d-453e-b539-8787dc905a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Prime</value>
      <webElementGuid>d7a7d2c8-9c83-4e68-ada4-50002bd5b6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-link-amazonprime&quot;)</value>
      <webElementGuid>0481d9d7-8e19-4e35-b2a1-68c0244f7ab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-link-amazonprime']</value>
      <webElementGuid>092ec54b-d1af-40a9-ad62-3b626f7a97a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-xshop']/a[8]</value>
      <webElementGuid>f3f77004-05f1-45ef-857b-a6f4e007a0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/prime?ref_=nav_cs_primelink_nonmember')]</value>
      <webElementGuid>bbdb7019-2fa1-48bb-83f9-4e141b58fff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[8]</value>
      <webElementGuid>d0732cbb-34d7-49b0-b699-8813c3a078be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/prime?ref_=nav_cs_primelink_nonmember' and @id = 'nav-link-amazonprime' and (text() = 'Prime' or . = 'Prime')]</value>
      <webElementGuid>b01b7a9c-c7e5-4065-9e0d-27fc415b6393</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
