<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Home  Kitchen</name>
   <tag></tag>
   <elementGuidId>37d9775d-ee52-4a44-8878-e15c9169aff0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-xshop']/a[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b7462b3f-9366-4599-8788-212250a5e153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Home-Kitchen/b/?ie=UTF8&amp;node=976442031&amp;ref_=nav_cs_home</value>
      <webElementGuid>9121b53b-7ae4-47f4-91d2-488c42a974d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a  </value>
      <webElementGuid>da2af581-e161-4ed3-b4bb-950e0caa8985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bfc2c82c-8b15-4146-967e-0be7e413542d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>f5fda29b-e678-4e33-a813-7d691e897dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>nav_cs_10</value>
      <webElementGuid>d63241b4-80d0-4381-8b44-d4b9e4df20c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>nav_cs_home</value>
      <webElementGuid>b3517cdd-77db-4c61-a76e-1c0412adf921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>rar6yr-6h40ly-6j1tmi-4jeqsi</value>
      <webElementGuid>c4907c09-4119-458a-81e4-f53a33fd5a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home &amp; Kitchen</value>
      <webElementGuid>3a6d1bb1-63c5-437d-9f46-9c64f566a233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-xshop&quot;)/a[@class=&quot;nav-a&quot;]</value>
      <webElementGuid>d4be3805-f734-46e1-bace-11544fdcd02d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-xshop']/a[11]</value>
      <webElementGuid>a1766f5c-152c-40ff-9ccd-428f6a03c495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Home &amp; Kitchen')]</value>
      <webElementGuid>7a6b2b36-2d28-48bd-b5f7-4b60b0f231bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Home-Kitchen/b/?ie=UTF8&amp;node=976442031&amp;ref_=nav_cs_home')]</value>
      <webElementGuid>dfbbf4ca-4dc5-43b0-9900-2c5c7094bfbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[11]</value>
      <webElementGuid>f9d3a187-decc-4826-9f3f-bd42d72a54a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Home-Kitchen/b/?ie=UTF8&amp;node=976442031&amp;ref_=nav_cs_home' and (text() = 'Home &amp; Kitchen' or . = 'Home &amp; Kitchen')]</value>
      <webElementGuid>00874159-bf81-4f0f-b1f7-b209fc76940a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
