<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Electronics</name>
   <tag></tag>
   <elementGuidId>f47e1f45-7f4d-4d15-a509-b20db48884c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-xshop']/a[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0404221a-496d-4cd5-acd2-d5f09fc6abe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/electronics/b/?ie=UTF8&amp;node=976419031&amp;ref_=nav_cs_electronics</value>
      <webElementGuid>057cc44a-c942-41ba-ad5c-3e4e65b8c506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a  </value>
      <webElementGuid>a7a84331-00ef-4a30-8fea-81d036af3a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>50082d3c-a073-4070-9281-d6ff3ad8883c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>c52bd406-cabb-4f5c-b533-d75389980a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>nav_cs_6</value>
      <webElementGuid>379c4acf-803f-4fca-867b-299cf004ab90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>nav_cs_electronics</value>
      <webElementGuid>572b4097-296d-47b5-bc59-b75d40a4135c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>q3ibif-sp11j1-2z7tyh-xcgwr7</value>
      <webElementGuid>694209a8-87c5-4627-9e8b-45eed3f3df3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Electronics </value>
      <webElementGuid>b39cf1a0-6a8b-4a56-b6bb-e4ab435e5f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-xshop&quot;)/a[@class=&quot;nav-a&quot;]</value>
      <webElementGuid>e7dbfcd3-baf1-4de4-acad-7af178f5eb07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-xshop']/a[7]</value>
      <webElementGuid>f78290ca-0e87-45eb-9a34-6d48ad6a445f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Electronics')]</value>
      <webElementGuid>2883bf68-34eb-4c19-ac36-dbbdb7f6dfa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/electronics/b/?ie=UTF8&amp;node=976419031&amp;ref_=nav_cs_electronics')]</value>
      <webElementGuid>f2711f3e-1b1d-4f3c-ac8d-9937cb192ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[7]</value>
      <webElementGuid>d66ac1d6-4749-4b2c-8746-30c873d4dfd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/electronics/b/?ie=UTF8&amp;node=976419031&amp;ref_=nav_cs_electronics' and (text() = ' Electronics ' or . = ' Electronics ')]</value>
      <webElementGuid>29124e46-7e51-4b49-a394-bf55c3210eb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
